package com.deepanshu.user.domain;

public enum TransactionType {
    ADD_MONEY,
    SEND_MONEY,
    RECEIVE_MONEY,
    BONUS,
    FREEZE_AMOUNT,
    CANCELLATION_FEE,
    REFUND_AMOUNT,
    ORDER_PAYMENT,
    REFUND_AGAINST_ORDER_CANCELLATION,
    REFUND_AGAINST_ORDER_RETURNED
}
